name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
course = input("Enter your course: ")
college = input("Enter your college name: ")
print("Student Details")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("Course:", course, "from", college)